import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', args: ['--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream'] });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, permissions: ['camera', 'microphone'], hasTouch: true, isMobile: true });
const page = await ctx.newPage();
const cdp = await ctx.newCDPSession(page);
page.on('console', m => console.log('CON:', m.type(), m.text().slice(0, 200)));
page.on('pageerror', e => console.log('PAGEERR:', String(e).slice(0, 500)));
await page.goto('http://localhost:4173/', { waitUntil: 'load' });
await page.waitForSelector('button[aria-label="Hold to record"]:not([disabled])', { timeout: 15000 });
const record = await page.getByRole('button', { name: 'Hold to record' }).boundingBox();
const point = { x: record.x + record.width / 2, y: record.y + record.height / 2, id: 1 };
await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [point] });
await page.waitForTimeout(2500);
const releaseVisible = await page.locator('button[aria-label="Release to stop recording"]').isVisible().catch(() => false);
console.log('releaseVisible:', releaseVisible);
await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
console.log('body snippet:', (await page.textContent('body')).slice(0, 300));
await page.screenshot({ path: 'scripts/probe3.png' });
await browser.close();
